<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="log4net" Version="3.3.2" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.9" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
      <PackageReference Include="RestSharp" Version="114.0.0" />
      <PackageReference Include="Selenium.WebDriver" Version="4.46.0" />
      <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="150.0.7871.11500" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Config\appsettings.json" />
      <None Remove="Config\log4net.config" />
      <Content Include="Config\log4net.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Config\appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
